### ISSUE TITLE
System tray icons are not showing on Polybar theme 1

### ISSUE THREAD

**Issue by rubusarbaro** [adi1090x/polybar-themes#74]
First of all, a little summary of my system:
**OS:** Ubuntu 20.04
**DE:** Regolith
**WM:** i3

I'm new at the world of WM. I modified the theme 1 config.ini file to look like this:
![barPoly](https://user-images.githubusercontent.com/61021296/93535047-cd260980-f90b-11ea-8110-aa3488f43624.png)
 
But I need to get back the system tray icons, specially Megasync.

Also, I need to place there the MOZC system tray icon. Mozc is a IME-like program used to type in Japanese in a ローマ字 (latin alphabet) based keyboard. It appears in Gnome at the top bar, like the picture. With out it, I can't write in Japanese.
![日本語のキーボード](https://user-images.githubusercontent.com/61021296/93535282-458cca80-f90c-11ea-91a6-51acf4ec807d.png)

Thank you.

**Comment by e-max** [comment]
Hi,
Do you have "tray-position = right" in your config file? 
You can read about it here https://github.com/polybar/polybar/wiki/Configuration

**Comment by hurondefuego** [comment]
Yes, it's in the right.
This the Bar section in the Config file:

`[bar/main]
monitor = 
width = 100%
height = 25
offset-x = 5%
offset-y = 2%
bottom = false
fixed-center = false
line-size = 2

background = ${color.bg}
foreground = ${color.fg}

border-size = 3
border-color = ${color.bg}

module-margin-left = 1
module-margin-right = 1

;==========================================================

font-0 = "Fantasque Sans Mono:pixelsize=12;2"
font-1 = "Material Icons:size=13;4"

;==========================================================

cursor-click = pointer

;tray-position = right
;tray-padding = 0
;tray-maxsize = 16
enable-ipc = true

scroll-up = i3wm-wsnext
scroll-down = i3wm-wsprev`

**Comment by e-max** [comment]
Yes, but as I can see this line is commented out.  All lines which starts with ";"  are ignored by polybar.

**Comment by adi1090x** [comment]
Repository Updated, Try again. Reopen if issues are not resolved.
Have a look at [Troubleshooting](https://github.com/adi1090x/polybar-themes#troubleshooting) for very common issues and how to resolve theme.
